"""Rename tag to item

Revision ID: a87c772709cd
Revises: fa4a9af40f32
Create Date: 2025-08-07 18:39:28.031229

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a87c772709cd'
down_revision = 'fa4a9af40f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('tag', 'item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('item', 'tag')

    # ### end Alembic commands ###
